ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
	dtbo-$(CONFIG_ARCH_SDM670) += \
		sdm670-cdp-overlay.dtbo \
		sdm670-mtp-overlay.dtbo \
		sdm670-rumi-overlay.dtbo \
		sdm670-qrd-overlay.dtbo \
		sdm670-qrd-sku2-overlay.dtbo \
		sdm670-pm660a-cdp-overlay.dtbo \
		sdm670-pm660a-mtp-overlay.dtbo \
		sdm670-external-codec-cdp-overlay.dtbo \
		sdm670-external-codec-mtp-overlay.dtbo \
		sdm670-external-codec-pm660a-cdp-overlay.dtbo \
		sdm670-external-codec-pm660a-mtp-overlay.dtbo \
		sdm670-usbc-cdp-overlay.dtbo \
		sdm670-usbc-mtp-overlay.dtbo \
		sdm670-usbc-pm660a-cdp-overlay.dtbo \
		sdm670-usbc-pm660a-mtp-overlay.dtbo \
		sdm670-usbc-external-codec-cdp-overlay.dtbo \
		sdm670-usbc-external-codec-mtp-overlay.dtbo \
		sdm670-usbc-external-codec-pm660a-cdp-overlay.dtbo \
		sdm670-usbc-external-codec-pm660a-mtp-overlay.dtbo \
		sdm670-tasha-codec-cdp-overlay.dtbo \
		sdm670-pm660a-tasha-codec-cdp-overlay.dtbo \
		sdm670-aqt1000-cdp-overlay.dtbo \
		sdm670-pm660a-aqt1000-cdp-overlay.dtbo \
		sdm710-cdp-overlay.dtbo \
		sdm710-mtp-overlay.dtbo \
		sdm710-qrd-overlay.dtbo \
		sdm710-qrd-sku2-overlay.dtbo \
		sdm710-pm660a-cdp-overlay.dtbo \
		sdm710-pm660a-mtp-overlay.dtbo \
		sdm710-external-codec-cdp-overlay.dtbo \
		sdm710-external-codec-mtp-overlay.dtbo \
		sdm710-external-codec-pm660a-cdp-overlay.dtbo \
		sdm710-external-codec-pm660a-mtp-overlay.dtbo \
		sdm710-usbc-cdp-overlay.dtbo \
		sdm710-usbc-mtp-overlay.dtbo \
		sdm710-usbc-pm660a-cdp-overlay.dtbo \
		sdm710-usbc-pm660a-mtp-overlay.dtbo \
		sdm710-usbc-external-codec-cdp-overlay.dtbo \
		sdm710-usbc-external-codec-mtp-overlay.dtbo \
		sdm710-usbc-external-codec-pm660a-cdp-overlay.dtbo \
		sdm710-usbc-external-codec-pm660a-mtp-overlay.dtbo \
		sdm710-tasha-codec-cdp-overlay.dtbo \
		sdm710-pm660a-tasha-codec-cdp-overlay.dtbo \
		sdm710-aqt1000-cdp-overlay.dtbo \
		sdm710-pm660a-aqt1000-cdp-overlay.dtbo \

sdm670-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-rumi-overlay.dtbo-base := sdm670.dtb
sdm670-qrd-overlay.dtbo-base := sdm670.dtb
sdm670-qrd-sku2-overlay.dtbo-base := sdm670.dtb
sdm670-pm660a-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-pm660a-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-external-codec-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-external-codec-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-external-codec-pm660a-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-external-codec-pm660a-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-pm660a-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-pm660a-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-external-codec-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-external-codec-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-external-codec-pm660a-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-usbc-external-codec-pm660a-mtp-overlay.dtbo-base := sdm670.dtb
sdm670-tasha-codec-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-pm660a-tasha-codec-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-aqt1000-cdp-overlay.dtbo-base := sdm670.dtb
sdm670-pm660a-aqt1000-cdp-overlay.dtbo-base := sdm670.dtb
sdm710-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-qrd-overlay.dtbo-base := sdm710.dtb
sdm710-qrd-sku2-overlay.dtbo-base := sdm710.dtb
sdm710-pm660a-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-pm660a-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-external-codec-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-external-codec-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-external-codec-pm660a-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-external-codec-pm660a-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-pm660a-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-pm660a-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-external-codec-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-external-codec-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-external-codec-pm660a-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-usbc-external-codec-pm660a-mtp-overlay.dtbo-base := sdm710.dtb
sdm710-tasha-codec-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-pm660a-tasha-codec-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-aqt1000-cdp-overlay.dtbo-base := sdm710.dtb
sdm710-pm660a-aqt1000-cdp-overlay.dtbo-base := sdm710.dtb

else
dtb-$(CONFIG_ARCH_SDM670) += sdm670-rumi.dtb \
	sdm670-mtp.dtb \
	sdm670-cdp.dtb \
	sdm670-qrd.dtb \
	sdm670-qrd-sku2.dtb \
	sdm670-pm660a-mtp.dtb \
	sdm670-pm660a-cdp.dtb \
	sdm670-external-codec-cdp.dtb \
	sdm670-external-codec-mtp.dtb \
	sdm670-external-codec-pm660a-cdp.dtb \
	sdm670-external-codec-pm660a-mtp.dtb \
	sdm670-usbc-cdp.dtb \
	sdm670-usbc-external-codec-cdp.dtb \
	sdm670-usbc-external-codec-mtp.dtb \
	sdm670-usbc-external-codec-pm660a-cdp.dtb \
	sdm670-usbc-external-codec-pm660a-mtp.dtb \
	sdm670-usbc-mtp.dtb \
	sdm670-usbc-pm660a-cdp.dtb \
	sdm670-usbc-pm660a-mtp.dtb \
	sda670-mtp.dtb \
	sda670-hdk.dtb \
	sda670-cdp.dtb \
	sdm670-tasha-codec-cdp.dtb \
	sdm670-pm660a-tasha-codec-cdp.dtb \
	sda670-pm660a-mtp.dtb \
	sda670-pm660a-cdp.dtb \
	sxr1120-lc-mtp.dtb \
	sxr1120-lc-external-codec-mtp.dtb \
	sxr1120-lc-cdp.dtb \
	sxr1120-lc-external-codec-cdp.dtb \
	qcs605-360camera.dtb \
	qcs605-mtp.dtb \
	qcs605-cdp.dtb \
	qcs605-external-codec-mtp.dtb \
	qcs605-lc-ipcamera.dtb \
	qcs605-lc-mtp.dtb \
	qcs605-lc-cdp.dtb \
	qcs605-lc-mtp-no-hdcp.dtb \
	sdm710-mtp.dtb \
	sdm710-cdp.dtb \
	sdm710-qrd.dtb \
	sdm710-qrd-sku2.dtb \
	sdm710-pm660a-mtp.dtb \
	sdm710-pm660a-cdp.dtb \
	sdm710-external-codec-cdp.dtb \
	sdm710-external-codec-mtp.dtb \
	sdm710-external-codec-pm660a-cdp.dtb \
	sdm710-external-codec-pm660a-mtp.dtb \
	sdm710-usbc-cdp.dtb \
	sdm710-usbc-external-codec-cdp.dtb \
	sdm710-usbc-external-codec-mtp.dtb \
	sdm710-usbc-external-codec-pm660a-cdp.dtb \
	sdm710-usbc-external-codec-pm660a-mtp.dtb \
	sdm710-usbc-mtp.dtb \
	sdm710-usbc-pm660a-cdp.dtb \
	sdm710-usbc-pm660a-mtp.dtb \
	sdm710-tasha-codec-cdp.dtb \
	sdm710-pm660a-tasha-codec-cdp.dtb \
	sxr1130-cdp.dtb \
	sxr1130-external-codec-cdp.dtb \
	sxr1130-mtp.dtb \
	sxr1130-external-codec-mtp.dtb \
	sxr1130-external-codec-pm660a-mtp.dtb \
	sxr1130-pm660a-mtp.dtb \
	sxr1130-usbc-external-codec-cdp.dtb \
	sxr1130-usbc-external-codec-mtp.dtb \
	sxr1130-usbc-external-codec-pm660a-mtp.dtb \
	sxr1130-usbc-mtp.dtb \
	sxr1130-usbc-pm660a-mtp.dtb \
	sxr1130-qrd.dtb \
	sxr1130-svr.dtb
endif

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
