#ifdef VENDOR_EDIT
#wen.luo@BSP.Kernel.Stability 2020/03/25 add for oplus kernel system
obj-$(CONFIG_OPLUS_SYSTEM_KERNEL)    += system/
#endif /* VENDOR_EDIT */

#ifdef OPLUS_FEATURE_POWERINFO_STANDBY
obj-$(CONFIG_OPLUS_WAKELOCK_PROFILER) += owakelock/
#endif /* OPLUS_FEATURE_POWERINFO_STANDBY */

#ifdef VENDOR_EDIT
obj-y     +=  oplus_healthinfo/
#endif /* VENDOR_EDIT */
